spring:
  application:
    name: encore
  banner:
    location: classpath:asciilogo.txt
  cloud:
    config:
      enabled: false

health:
  config:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
  health:
    redis:
      enabled: true

service:
  name: encore

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic

encore-settings:
  redis-key-prefix: ${service.name}
  poll-initial-delay: 10s
  poll-delaly: 5s


springdoc:
  paths-to-exclude: /profile/encoreJobs,/profile
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
